from app import db
from app.model import Mechanism, Post

db.create_all()
m = Mechanism(32046, company='nmtp', type='usm', model='PowerTrack', number=1, name='PowerTrack-1')
db.session.add(m)
m = Mechanism(32047, company='nmtp', type='usm', model='PowerTrack', number=2, name='PowerTrack-2')
db.session.add(m)
m = Mechanism(32711, company='nmtp', type='usm', model='Edge', number=3, name='Edge-3')
db.session.add(m)
m = Mechanism(32740, company='nmtp', type='usm', model='Edge', number=4, name='Edge-4')
db.session.add(m)
m = Mechanism(32770, company='nmtp', type='usm', model='Screen', number=5, name='Screen-5')
db.session.add(m)
m = Mechanism(32771, company='nmtp', type='usm', model='Screen', number=6, name='Screen-6')
db.session.add(m)
m = Mechanism(32772, company='nmtp', type='usm', model='Screen', number=7, name='Screen-7')
db.session.add(m)
m = Mechanism(32773, company='nmtp', type='usm', model='Screen', number=8, name='Screen-8')
db.session.add(m)
m = Mechanism(32941, company='nmtp', type='usm', model='Electric', number=9, name='Electric-9')
db.session.add(m)
m = Mechanism(32942, company='nmtp', type='usm', model='Electric', number=10, name='Electric-10')
db.session.add(m)
m = Mechanism(33287, company='nmtp', type='usm', model='Edge', number=11, name='Edge-11')
db.session.add(m)
m = Mechanism(32777, company='nmtp', type='sennebogen', model='860', number=1, name='Sennebogen-1')
db.session.add(m)
db.session.commit()
a = [mech.id for mech in Mechanism.query.all()]
print(a)

