"""posts table1

Revision ID: 13ff22b8a06f
Revises: 
Create Date: 2019-11-04 11:13:21.652736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ff22b8a06f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanism', 'company',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('mechanism', 'model',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('mechanism', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('mechanism', 'number',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('mechanism', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanism', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('mechanism', 'number',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('mechanism', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('mechanism', 'model',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('mechanism', 'company',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
