last:
	bash nmtport/middleware/last.sh

kran:
	bash nmtport/middleware/kran.sh

usm:
	bash nmtport/middleware/usm.sh

find:
	cat  /var/log/nginx/access.log | rg "number=$n\&" | rg count=

stat:
	sudo systemctl status nmtport.service
